apiVersion: v1
kind: Namespace
metadata:
  name: hello-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: hello
  name: hello
  namespace: hello-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
        - image: localhost:30100/hello:latest
          imagePullPolicy: Always
          name: hello
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello-demo
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
